# Generated by Django 5.1.1 on 2024-11-14 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_order_details_order_detail'),
        ('shop', '0002_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_detail',
            new_name='Order_details',
        ),
    ]
